"""Pydantic schemas. Shared interface between capture, layers, storage, and report.

All cross-module types live here. Do not re-define the same concept elsewhere.
"""

from consent_audit.models.audit import (
    AuditReport,
    CaptureBundle,
    ChangeEvent,
    EffortScore,
    EffortSubFeature,
    ElementRef,
    EventLogRef,
    FramingResult,
    Layer1Result,
    Layer2Result,
    Layer3Result,
    LayerSnapshot,
    MultimodalFingerprint,
    PathOutcome,
    ScreenshotBBox,
    TopicCoverageResult,
    TransparencyResult,
    UnbiasedChoiceResult,
    WeeklySummary,
)
from consent_audit.models.dimensions import (
    BiasLevel,
    ChangeEventType,
    DisclosureTopic,
    EffortCategory,
    FramingMechanism,
    LetterGrade,
    Pathway,
    Tier,
)

__all__ = [
    "AuditReport",
    "BiasLevel",
    "CaptureBundle",
    "ChangeEvent",
    "ChangeEventType",
    "DisclosureTopic",
    "EffortCategory",
    "EffortScore",
    "EffortSubFeature",
    "ElementRef",
    "EventLogRef",
    "FramingMechanism",
    "FramingResult",
    "Layer1Result",
    "Layer2Result",
    "Layer3Result",
    "LayerSnapshot",
    "LetterGrade",
    "MultimodalFingerprint",
    "PathOutcome",
    "Pathway",
    "ScreenshotBBox",
    "Tier",
    "TopicCoverageResult",
    "TransparencyResult",
    "UnbiasedChoiceResult",
    "WeeklySummary",
]
